extraScrapeConfigs: |
  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']
    scheme: http
    bearer_token: "VAULT_TOKEN"
    static_configs:
    - targets: ['10.9.99.10:8200']
  - job_name: consul
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/v1/agent/metrics'
    scheme: http
    params:
      format: ['prometheus']
    static_configs:
    - targets: ['10.9.99.10:8500']
  - job_name: nomad
    consul_sd_configs:
    - server: '10.9.99.10:8500'
      services: ['nomad-client', 'nomad']
    relabel_configs:
    - source_labels: ['__meta_consul_tags']
      regex: '(.*)http(.*)'
      action: keep
    scrape_interval: 5s
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']
